version: '3.8'

services:
  airdrop_db:
    image: mysql:8
    container_name: airdrop_db
    env_file:
      - .env.sql.deploy
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - db

  airdrop_app:
    build: .
    container_name: airdrop_app
    depends_on:
      - airdrop_db
    env_file:
      - .env.deploy
    restart: always
    networks:
      - web
      - db

volumes:
  mysql-data:

networks:
  db:
  web:
    name: web
    external: true
